### ISSUE TITLE
Consider handing PyPI package over to dwolfpi that hosts a more maintained py3 compat version

### ISSUE THREAD

**Issue by graingert** [dropbox/python-zxcvbn#19]
https://github.com/dwolfhub/zxcvbn-python/issues/23

**Comment by rpearl** [comment]
I no longer work at Dropbox and don't have any say over this repo at this point, sorry!

**Comment by graingert** [comment]
@rpeal could you add dwolfpi to https://pypi.python.org/pypi/zxcvbn ?

**Comment by graingert** [comment]
@rpearl could you add dwolfpi to https://pypi.python.org/pypi/zxcvbn ?

**Comment by graingert** [comment]
@rpearl ping

**Comment by rpearl** [comment]
While I control the zxcvbn package on pypi, given that the IP belongs to Dropbox, please contact them. https://www.dropbox.com/contact

**Comment by thedrow** [comment]
I just pinged @gvanrossum directly. I'm hoping he can help speed this up.

**Comment by graingert** [comment]
This is about ownership of the PyPI entry. Currently zxcvbn is unmaintained by @rpearl and python-zxcvbn is maintained by @dwolfhub

**Comment by gvanrossum** [comment]
But even if I wanted to I couldn't change the PyPI entry's ownership,
because it's @rpearl's. Given that Dropbox itself uses @dwolfhub's version,
I think it's reasonable to say that if @rpearl agrees he can transfer
ownership to @dwolfhub, as long as you keep the original
https://pypi.python.org/pypi/zxcvbn/1.0 entry around (for those poor souls
who want to try out the original).

Or do you want an official legal opinion from Dropbox? I can ask our lawyer
but it will take a while. Let me know if you need this.

**Comment by dwolfhub** [comment]
@gvanrossum I see no reason to remove 1.0. I'm sure there are projects still using it.

@rpearl my pypi username is dwolfpi FYI

Is it possible to add a message to the README in this repository to note that this version is deprecated? Just trying to avoid confusion.

**Comment by gvanrossum** [comment]
OK, I added a note to the README (https://github.com/dropbox/python-zxcvbn/pull/20). @rpearl you have my blessing to had over the PyPI project to @dwolfhub.

**Comment by rpearl** [comment]
Okay, with that word @gvanrossum / Dropbox, I've added @dwolfhub as an owner of the pypi project. Sorry for the confusion here; I just didn't want to hand over a thing which (while in my control) was developed solely while at Dropbox.

**Comment by gvanrossum** [comment]
Thanks @rpearl! You did the right thing here.
